### ISSUE TITLE
源码呢？

### ISSUE THREAD

**Issue by ant1dote** [HuCaoFighting/Swin-Unet#10]
啥时候上传源码？我想学习学习。。

**Comment by SynMarc** [comment]
+1

**Comment by whatcolor1** [comment]
+10086

**Comment by nmxian** [comment]
+11111

**Comment by ant1dote** [comment]
我看了他别的项目，好像都没有源码。老哥钓鱼有一手的。

**Comment by nmxian** [comment]
> 我看了他别的项目，好像都没有源码。老哥钓鱼有一手的。

钓鱼？什么意思？

**Comment by ant1dote** [comment]
他文章说是给公开了，但是又不上传，他别的项目也没有代码，那不是玩我呢吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月24日(星期四) 晚上6:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HuCaoFighting/Swin-Unet] 源码呢？ (#10)





  
我看了他别的项目，好像都没有源码。老哥钓鱼有一手的。
  
钓鱼？什么意思？

**Comment by HuCaoFighting** [comment]
The codes have been publised

**Comment by Flyingdog-Huang** [comment]
> 他文章说是给公开了，但是又不上传，他别的项目也没有代码，那不是玩我呢吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年6月24日(星期四) 晚上6:59 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [HuCaoFighting/Swin-Unet] 源码呢？ (#10) 我看了他别的项目，好像都没有源码。老哥钓鱼有一手的。 钓鱼？什么意思？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

ali的更流氓，2021顶会的两篇paper，说是公开code和dataset，一共是2个repo和2个datasets，但是一直到现在都只有一个dataset，yue~~
