### ISSUE TITLE
非常好的工作，请问在ACDC数据集上训练的超参数如何设置的

### ISSUE THREAD

**Issue by DaydreamerH** [HuCaoFighting/Swin-Unet#110]
你好，我想问一下在本文中提到的在ACDC数据集上训练的超参数具体是多少，有保存嘛？

我曾尝试在半监督学习任务中将该模型在ACDC数据集上训练，但发现难以训练出理想的效果，非常容易出现过拟合或是欠拟合（最好的结果是mean dice为87.2，而同样的方法使用UNet的结果为88.55），在ACDC数据集上训练SwinUNet的相关记录或技巧在互联网上很难找到。

所以来问一下，有无一些需要注意的事情。

谢谢！

**Comment by LebronMX-A** [comment]
Hello, when I train the ACDC dataset, it takes several hours to train an epoch, this is a normal phenomenon, if you follow this time, 150 epochs will be immeasurable

**Comment by DaydreamerH** [comment]
OK，I'll try it later.
