### ISSUE TITLE
Unable to adapt to different resolution

### ISSUE THREAD

**Issue by KruskalLin** [HuCaoFighting/Swin-Unet#12]
Hi, thanks for your contribution. The model is unable to adapt to different resolutions except for 224 for both height and width. The error often occurs as
```python
RuntimeError: shape '[xxx, xxx, xxx, xxx, xxx]' is invalid for input of size xxx
```

**Comment by weiaicunzai** [comment]
hi, did you sovle that? I have aslo encountered this problem

**Comment by KruskalLin** [comment]
No. However, the Swin model itself requires an input size of 224. It also cannot adapt to resolutions other than 224. I choose to crop the original image for training.

**Comment by weiaicunzai** [comment]
> No. However, the Swin model itself requires an input size of 224. It also cannot adapt to resolutions other than 224. I choose to crop the original image for training.

Ok, thanks for your replay.

**Comment by DeanChan** [comment]
Hi @KruskalLin, you may try other resolutions that are dividable by 28 (patch_size=4 * window_size=7) such as 252, 280, 308, 336, etc.
