### ISSUE TITLE
How is Unet trained?

### ISSUE THREAD

**Issue by a313071162** [HuCaoFighting/Swin-Unet#14]
Hi there!
Thank you for your innovative work.
I want to ask how your Unet and attention-unet are trained. I tried many times and I couldn’t achieve that effect.

Looking forward to your reply.
Best wish!!!

**Comment by HuCaoFighting** [comment]
Hello, thanks for your interest. We implement the Unet and Attention-unet based on this link (https://github.com/bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets) and keep the same parameter settings to train Unet and Attention-unet on Synapse dataset.

**Comment by a313071162** [comment]
Are your parameters consistent with swin-unet?

Looking forward to your reply.
Best wish!!!

**Comment by HuCaoFighting** [comment]
Yes, the parameter settings keep the same with swin-unet.

**Comment by a313071162** [comment]
Thank you for your help!!!
