### ISSUE TITLE
ACDC dataset preprocessing

### ISSUE THREAD

**Issue by zhouzhenghong-gt** [HuCaoFighting/Swin-Unet#18]
Hi! Thanks for your nice work! 
And I'd like to ask what is the preprocessing method of the ACDC dataset? I did not find relevant information in TransUNet and Swin-Unet.

**Comment by HuCaoFighting** [comment]
Hello, the ACDC dataset we used is provided by TransUnet's author. You can send an email to TransUnet's author to get more detailed information.

**Comment by cwpl** [comment]
@HuCaoFighting I want to know if ACDC is handled in the same way as Synapse? Thanks!

**Comment by Allen123star** [comment]
Hi, Thanks for your work, I found  TransUnet's author doesn't provide the ACDC dataset code either...
