### ISSUE TITLE
对于使用代码的许可

### ISSUE THREAD

**Issue by Reself-C** [HuCaoFighting/Swin-Unet#19]
您好，您团队的工作精致且富有成效。
我是ZJU的一名学生，我想基于您团队的研究成果参加一个学术性的桥梁语义分割比赛，因此来请求许可。
同时，我的目标是从1920*1080的image中分割出640*360（即1/9像素）级别的语义分割即可，想请问对于这样的需求，您有什么建议吗

**Comment by HuCaoFighting** [comment]
谢谢哈。比赛当然可以使用咯。对于高分辨率的图像，建议看下XCIT（https://github.com/facebookresearch/xcit），这个paper的作者说是在高分辨率的效果不错。

**Comment by Reself-C** [comment]
@HuCaoFighting 我已经在224尺度上使用0.01Lr训练出了比较满意的结果，想请问这个网络可以支持矩形的输入图像吗（只要长宽都是32的倍数）？

**Comment by HuCaoFighting** [comment]
不支持矩形，swin的widow设置和输入尺寸相关。为了实现last stage的全局，widow size等于last stage的尺寸，224， window 7， 384 ，window 12. 其他的自己根据实际情况相应调整就好
