### ISSUE TITLE
ACDC数据的随机划分

### ISSUE THREAD

**Issue by ZhifangDeng** [HuCaoFighting/Swin-Unet#25]
你好，数据我已经下载。我看论文中，关于此ACDC数据集的划分是随机进行划分的，为了更好的对比结果，方便分享一下你们的数据集划分和预处理情况吗？如果有训练和测试代码更好，1262620440@qq.com，非常感谢

**Comment by tjpustoy** [comment]
哥们 数据能不能发我一下，是原始数据呢还是预处理好的数据啊

**Comment by tjpustoy** [comment]
> 你好，数据我已经下载。我看论文中，关于此ACDC数据集的划分是随机进行划分的，为了更好的对比结果，方便分享一下你们的数据集划分和预处理情况吗？如果有训练和测试代码更好，[1262620440@qq.com](mailto:1262620440@qq.com)，非常感谢

你好，数据能不能发我一份呢？我找不到数据，你的是原始数据还是预处理好后的数据呢？

**Comment by wtkszzz** [comment]
> > 你好，数据我已经下载。我看论文中，关于此ACDC数据集的划分是随机进行划分的，为了更好的对比结果，方便分享一下你们的数据集划分和预处理情况吗？如果有训练和测试代码更好，[1262620440@qq.com](mailto:1262620440@qq.com)，非常感谢
> 
> 你好，数据能不能发我一份呢？我找不到数据，你的是原始数据还是预处理好后的数据呢？

你好，请问你拿到ACDC数据集和预处理ACDC的代码了吗
