### ISSUE TITLE
when the code will release

### ISSUE THREAD

**Issue by caoyifeng001** [HuCaoFighting/Swin-Unet#3]
when the code will release

**Comment by wuliwan** [comment]
when the code will release

**Comment by Siyuan89** [comment]
when the code will release

**Comment by kjp96** [comment]
when the code will release

**Comment by Lature-Yang** [comment]
when the code will release

**Comment by Haofeng-Cheng** [comment]
when the code will release

**Comment by siyue520** [comment]
when the code will release

**Comment by HuCaoFighting** [comment]
The codes have been published
