### ISSUE TITLE
different data

### ISSUE THREAD

**Issue by FrankWuuu** [HuCaoFighting/Swin-Unet#32]
hello @HuCaoFighting ,
I want to use the swin_unet for  segmentation task, and the data is end with `png` or `jpg` rather than `.nii.gz`.
So I need to change the `dataset_synapse.py`,  I tried many times but I failed. Coul you give me some advice?
Thanks!

**Comment by standingbychen** [comment]
You can try to write a new dataloader for your specific dataset.
I do so to fit my task.

**Comment by ASguoyue** [comment]
> 你好@HuCaoFighting， 我想使用swin_unet进行分割任务，数据以`png`or结尾，`jpg`而不是`.nii.gz`。 所以我需要更改`dataset_synapse.py`，我尝试了很多次但我失败了。你能给我一些建议吗？ 谢谢！

你好请问一下这个修改好了吗

**Comment by FrankWuuu** [comment]
> > 你好@HuCaoFighting， 我想使用swin_unet进行分割任务，数据以`png`or结尾，`jpg`而不是`.nii.gz`。 所以我需要更改`dataset_synapse.py`，我尝试了很多次但我失败了。你能给我一些建议吗？ 谢谢！
> 
> 你好请问一下这个修改好了吗

我用了一个新的
