### ISSUE TITLE
Is it convenient to provide a preprocessed data file?

### ISSUE THREAD

**Issue by tjpustoy** [HuCaoFighting/Swin-Unet#42]
Hello, I have sent an email to the mailbox in the Readme, hoping to get a copy of the preprocessed data, but unfortunately I did not reply. So ask again on Issue, is it convenient to provide a preprocessed data file?Thank you very much if you can reply to the email

**Comment by caoyuanbao** [comment]
Me too! Welcome the Author@HuCaoFighting send a copy of the preprocessed data to 1752271883@qq.com. Thank you!!!!

**Comment by HuCaoFighting** [comment]
Since we get the preprocessed data from TransUnet's author, we do not have the right to distribute the data file. As I write in the ReadMe, you should send an Email to jienengchen01 AT gmail.com to request the preprocessed data.

**Comment by wtkszzz** [comment]
> 



> 你好，我已经发邮件到Readme里面的邮箱，希望能拿到一份预处理后的数据，可惜没有回复。所以在Issue上再问一下，提供预处理的数据文件方便吗？如果能回复邮件非常感谢

请问你获得预处理的数据了吗，我给作者发邮件没有得到回复，如果你拿到预处理后的数据可以分享一下吗 邮箱：739371273@qq.com

**Comment by caoshiwen1** [comment]
> 自动回复：你好，我已经收到你的邮件，待我细看后联系曹洁

请问你获得预处理的数据了吗，我也给作者发邮件没有得到回复，如果你拿到预处理后的数据可以分享一下吗 邮箱：1816383535@qq.com

**Comment by caoyuanbao** [comment]
自动回复：你好，我已经收到你的邮件，待我细看后联系曹洁

**Comment by Chenguang-Wang** [comment]
Great work! me is learning you're paper and code recently.
Can you share teh preprocessed synapse dataset with me([wangchenguang@stu.scu.edu.cn](mailto:wangchenguang@stu.scu.edu.cn))?
I sent an email to teh author of TransUnet but did not get a reply.
Thank you!

**Comment by caoyuanbao** [comment]
自动回复：你好，我已经收到你的邮件，待我细看后联系曹洁

**Comment by Sept30** [comment]
Can someone share the preprocessed synapse dataset with me(mailto:sept_30@stu.haut.edu.cn)?
I sent an email to the author of TransUnet but did not get a reply.
Thank you!

**Comment by caoyuanbao** [comment]
自动回复：你好，我已经收到你的邮件，待我细看后联系曹洁

**Comment by L-A-Sandhu** [comment]
share data at laeeq.aslam.100@gmail.com 
if possible

**Comment by ninedow** [comment]
I also sent an email to the author of TransUnet but did not get a reply.
Can someone share the preprocessed synapse dataset with me(email: huiyizhang11@gmail.com)?
Thank you very much!

**Comment by JuntuoWang** [comment]
> I also sent an email to the author of TransUnet but did not get a reply.
> Can someone share the preprocessed synapse dataset with me(email:
Juntuo.Wang20@student.xjtlu.edu.cn)

**Comment by caoyuanbao** [comment]
自动回复：你好，我已经收到你的邮件，待我细看后联系曹洁

**Comment by June-phy** [comment]
Can someone share the preprocessed synapse dataset with me(mailto:[qxshan@mail.ustc.edu.cn](mailto:sept_30@stu.haut.edu.cn))?
I sent an email to the author of TransUnet but did not get a reply.
Thank you!

**Comment by Smile-QT** [comment]
Can you share the preprocessed synapse dataset (mailto:1309733271@qq.com)?

I emailed the author of TransUnet but got no response.

thank you very much!

**Comment by Smile-QT** [comment]
Can you share the preprocessed synapse dataset (mailto:1309766271@qq.com)?

I emailed the author of TransUnet but got no response.

thank you very much!

**Comment by Smile-QT** [comment]
> > 
> 
> > 你好，我已经发邮件到Readme里面的邮箱，希望能拿到一份预处理后的数据，可惜没有回复。所以在Issue上再问一下，提供预处理的数据文件方便吗？如果能回复邮件非常感谢
> 
> 请问你获得预处理的数据了吗，我给作者发邮件没有得到回复，如果你拿到预处理后的数据可以分享一下吗 邮箱：[739371273@qq.com](mailto:739371273@qq.com)
不好意思打扰一下，你获得预处理的数据了吗?如果获得了能分享一下吗？谢谢（1309766271@qq.com）

**Comment by Smile-QT** [comment]
你好！请问CBSD68数据集是怎样处理的，swin接收的图片的大小长和宽是一样的并且是固定的，但是CBSD68数据集大小和长、宽都是不固定的，这个问题你们是怎样处理的，能提供一下代码吗？

**Comment by Smile-QT** [comment]
你好！请问CBSD68数据集是怎样处理的，swin接收的图片的大小长和宽是一样的并且是固定的，但是CBSD68数据集图片大小和长、宽都是不固定的，这个问题你们是怎样处理的，能提供一下代码吗？

**Comment by 258yujin** [comment]
Can someone share the preprocessed synapse dataset with me(email:2097798794@qq.com)?
I sent an email to the author of TransUnet but did not get a reply.
Thank you!

**Comment by caoyuanbao** [comment]
自动回复：你好，我已经收到你的邮件，待我细看后联系曹洁

**Comment by Ban1-cmyk** [comment]
呜呜呜有没有人能给我发一份处理过的数据集（1249864420@qq.com），给作者发邮箱没有回复，拜托拜托。

**Comment by caoyuanbao** [comment]
自动回复：你好，我已经收到你的邮件，待我细看后联系曹洁

**Comment by qyh0101** [comment]
请问你获得预处理的数据了吗，可以分享一下吗?谢谢你 邮箱：838542335@qq.com

**Comment by caoyuanbao** [comment]
自动回复：你好，我已经收到你的邮件，待我细看后联系曹洁

**Comment by yang-0330** [comment]
可以分享一下预处理的数据么 谢谢！ 邮箱：12232610@mail.sustech.edu.cn

**Comment by caoyuanbao** [comment]
自动回复：你好，我已经收到你的邮件，待我细看后联系曹洁

**Comment by SKR** [comment]
Can you share preprocessed data? E-mail to  jiangpeng8766@gmail.com

**Comment by caoyuanbao** [comment]
自动回复：你好，我已经收到你的邮件，待我细看后联系曹洁

**Comment by HuCaoFighting** [comment]
See the link https://drive.google.com/drive/folders/1ACJEoTp-uqfFJ73qS3eUObQh52nGuzCd?usp=sharing

**Comment by caoyuanbao** [comment]
自动回复：你好，我已经收到你的邮件，待我细看后联系曹洁

**Comment by June-phy** [comment]
Thank you so much !!!

从 Windows 版邮件发送

发件人: Hu Cao
发送时间: 2023年5月12日 3:09
收件人: HuCaoFighting/Swin-Unet
抄送: June-phy; Comment
主题: Re: [HuCaoFighting/Swin-Unet] Is it convenient to provide apreprocessed data file? (Issue #42)

See the link https://drive.google.com/drive/folders/1ACJEoTp-uqfFJ73qS3eUObQh52nGuzCd?usp=sharing
