### ISSUE TITLE
我有一个问题，紧急求助！

### ISSUE THREAD

**Issue by victory3398** [HuCaoFighting/Swin-Unet#57]
我试着搭建自己的Swin-Unet,首先我把 swin的每个输出进行view(),然后再用upsample()搭建一个上采样头，但是分割结果却很差劲 整个图片显示同一个颜色。我不知道自己哪里出问题了，请问对swin的输出直接view()操作合适么？和rearrange有什么区别?

**Comment by HuCaoFighting** [comment]
对于pure Transformer的模型，用预训练好的参数进行初始化对最后的性能好坏影响很大。个人觉得你搭建的模型效果不好和view操作无关，你可以check下你的参数初始化。至于整个图片同一个颜色这就需要检查你的code。

**Comment by HuCaoFighting** [comment]
closed

**Comment by long123524** [comment]
你好，对于其他尺寸的图片比如256x256的应该如何进行修改呢？目前的Swinunet只能用来训练224x244的，你有好的方法吗？感谢
