### ISSUE TITLE
关于预处理数据集请求

### ISSUE THREAD

**Issue by NickWang1122** [HuCaoFighting/Swin-Unet#69]
您好，由于无法联系上“jienengchen01”，自己处理起来有些困难，能否将您的预处理数据集分享一下，万分感谢，期待您的回复。

**Comment by liuwj2000** [comment]
同求，联系不上+1

**Comment by Drwr97** [comment]
I also want this code. My email is 1158157431@qq.com

Thank you very much.

**Comment by a1486364635** [comment]
急需数据集预处理代码，email：1486364635@qq.com，非常感谢

**Comment by RuiyangJu** [comment]
同求，感谢!

**Comment by yxy0102** [comment]
同求处理过的数据集，1471834556@qq.com

**Comment by Ban1-cmyk** [comment]
联系不上jienengchen01，同求处理过的数据集，拜托拜托，呜呜呜马上就要组会报告了，救救孩子。
1249864420@qq.com

**Comment by HuCaoFighting** [comment]
Please email jienengchen01 AT gmail.com to get the processed datasets.

**Comment by Kimmm-pzl** [comment]
> 急需数据集预处理代码，email：[1486364635@qq.com](mailto:1486364635@qq.com)，非常感谢

请问作者有发布预处理的代码吗？
