### ISSUE TITLE
ACDC数据集下载

### ISSUE THREAD

**Issue by wangqingbin** [HuCaoFighting/Swin-Unet#74]
作者你好，请问一下ACDC数据集在哪里下载，还有预处理的代码可以分享一下吗

**Comment by 870572761** [comment]
借楼，我也需要一份数据集用于研究，我的邮箱是20203100347@hainan.edu.cn,如果作者能帮助到我，我将万分感激（p_q）

**Comment by HuCaoFighting** [comment]
Please email jienengchen01 AT gmail.com to get the processed datasets.
