### ISSUE TITLE
Request the Preprocessed Data

### ISSUE THREAD

**Issue by tommasogattari** [HuCaoFighting/Swin-Unet#78]
Hi,
I'm interested in your project. Could you share the preprocessed data with me too?
Thank you in advance.
Email: [tommasogattari@gmail.com](mailto:tommasogattari@gmail.com)

**Comment by EvgeniaChroni** [comment]
As the authors indicate, you can find the preprocessed data from this repo[https://github.com/Beckschen/TransUNe](url)
Specifically from this link [https://drive.google.com/drive/folders/1ACJEoTp-uqfFJ73qS3eUObQh52nGuzCd?usp=sharing](url). 

However, I cannot reproduce results.

**Comment by HuCaoFighting** [comment]
See the link https://drive.google.com/drive/folders/1ACJEoTp-uqfFJ73qS3eUObQh52nGuzCd?usp=sharing

**Comment by HuCaoFighting** [comment]
See the link https://drive.google.com/drive/folders/1ACJEoTp-uqfFJ73qS3eUObQh52nGuzCd?usp=sharing

**Comment by Kimmm-pzl** [comment]
Hello, can you provide the script for preprocessing data? This helped me a lot, thanks!

Best
Kim

**Comment by Kimmm-pzl** [comment]
> See the link https://drive.google.com/drive/folders/1ACJEoTp-uqfFJ73qS3eUObQh52nGuzCd?usp=sharing

Hello, can you provide the script for preprocessing data? This helped me a lot, thanks!

Best
Kim
