### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by xdz7799** [HuCaoFighting/Swin-Unet#84]
作者您好，看了您的模型感觉非常棒，但是我运行了一下test.py只是生成了两个指标，想问一下该如何生成类似于论文中的可以看出分割效果的效果图，还有就是这个模型可以做输入为二维的病理图像的语义分割吗。谢谢您的解答！

**Comment by HuCaoFighting** [comment]
您好，您的邮件已收到。

**Comment by xdz7799** [comment]
希望可以得到您的解答，谢谢。

**Comment by HuCaoFighting** [comment]
您好，可以用来做二维病理图像的分割任务。可视化是用的另外的demo脚本。我抽空看下整理出来更新一下。

**Comment by xdz7799** [comment]
非常感谢您的回复，还有个问题想要请教一下您，如果想用这个模型去做一个二维病理图像的分割任务，大体应该做哪些修改呢。

**Comment by HuCaoFighting** [comment]
输入的数据加载部分和分割的头对应的类别，其他基本不用改。

**Comment by xdz7799** [comment]
谢谢您的回复，我看预训练模型的尺寸是224的，意思是最好用224的图片训练吗，如果我想用512的图片训练会不会在效果上没有这么好呢

**Comment by xdz7799** [comment]
还有一个问题想请教一下您，应该修改什么地方可以让模型不使用预训练权重，从头开始训练呢，期望您的回复。

**Comment by HuCaoFighting** [comment]
改成512X512的话要改对应的swin的window size。 Swin的window size是保证最后stage是global attention。你看原swin 对应的不同输入size的window size是对应改动的。

**Comment by HuCaoFighting** [comment]
不加载权重就ok

**Comment by xdz7799** [comment]
parser.add_argument('--cfg', type=str, required=True, metavar="FILE", help='path to config file', )请问作者是把这句默认值置为空字符吗

**Comment by HuCaoFighting** [comment]
你看看codes里面有

**Comment by HuCaoFighting** [comment]
no more questions

**Comment by NJNUCS** [comment]
> 您好，可以用来做二维病理图像的分割任务。可视化是用的另外的demo脚本。我抽空看下整理出来更新一下
您好，感谢您卓越的工作，请问您在多器官分割上的分割可视化代码整理出来了嘛，我想要拿来做研究，谢谢

**Comment by algwang** [comment]
> 作者您好，看了您的模型感觉非常棒，但是我运行了一下test.py只是生成了两个指标，想问一下该如何生成类似于论文中的可以看出分割效果的效果图，还有就是这个模型可以做输入为二维的病理图像的语义分割吗。谢谢您的解答！

您好，我想问下处理自己数据集的时候怎么对数据集进行划分路径
