### ISSUE TITLE
Can you public the datasets?

### ISSUE THREAD

**Issue by bkai-research** [HuCaoFighting/Swin-Unet#9]
Hi, can you public the datasets and your split into training/validation/test sets?

**Comment by HuCaoFighting** [comment]
Sorry, we can't public the dataset. Because the preprocessed datasets we used are provided by TransUnet's authors. You can send an email to TransUnet's authors to get the dataset.

**Comment by Zabiny** [comment]
Can I get the email of the author?Thank you very much

**Comment by Interesting6** [comment]
> Sorry, we can't public the dataset. Because the preprocessed datasets we used are provided by TransUnet's authors. You can send an email to TransUnet's authors to get the dataset.

TransUnet's authors have no response, maybe they are too busy to check the email box, or the email was spammed. Could you please send me a preprocessed or original dataset?  My email is chenymcan AT gmail.
thank you!

**Comment by Tensor-king** [comment]
@Interesting6  Hello,my friend,do you have data now?can you send to me?thank you very much! my email :zyf1787594682@163.com

**Comment by Zxl19990529** [comment]
@Interesting6  Hi, can you send me a copy too? My email is : zhangxinliang@tju.edu.cn

**Comment by ninedow** [comment]
> > 很抱歉，我们无法公开数据集。因为我们使用的预处理数据集是由TransUnet的作者提供的。您可以向 TransUnet 的作者发送电子邮件以获取数据集。
> 
> TransUnet的作者没有回应，也许他们太忙而无法检查电子邮件框，或者电子邮件被垃圾邮件。你能给我一个预处理或原始的数据集吗？我的电子邮件是chenymcan AT gmail。 谢谢！

Hello, can send me the data too? Thank you very much! My email is: huiyizhang11@gmail.com

**Comment by zyqdsn** [comment]
> > Sorry, we can't public the dataset. Because the preprocessed datasets we used are provided by TransUnet's authors. You can send an email to TransUnet's authors to get the dataset.
> 
> TransUnet's authors have no response, maybe they are too busy to check the email box, or the email was spammed. Could you please send me a preprocessed or original dataset? My email is chenymcan AT gmail. thank you!

Hello my friend，do you get the data now, I wonder if you could send me a copy，thank you so much

**Comment by HuCaoFighting** [comment]
您好，您的邮件已收到。

**Comment by zyqdsn** [comment]
@HuCaoFighting 
Hello my friend，I have recently read your paper about SwinUNet. The work was so interesting and it was attractive to me.I want to reproduce the results in the article. So I am wondering if you could kindly send me the processed ACDC and Synapse dataset. The transunet's author  didn't reply to me. I promise to use it for research only. Thank you very much for your kind consideration.

**Comment by Zabiny** [comment]
Sorry




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Wednesday, Sep 14, 2022 2:33 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [HuCaoFighting/Swin-Unet] Can you public the datasets? (#9)





 
@Interesting6 Hello my friend, do you get the data now? Could  you send to me? hank you very much! my ***@***.***

**Comment by zyqdsn** [comment]
Could you send the processed ACDC dataset to me? I promise to use it for research only. Thank you so much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuCaoFighting/Swin-Unet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月14日(星期三) 下午2:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuCaoFighting/Swin-Unet] Can you public the datasets? (#9)





 您好，您的邮件已收到。

**Comment by wangqingbin** [comment]
> Sorry, we can't public the dataset. Because the preprocessed datasets we used are provided by TransUnet's authors. You can send an email to TransUnet's authors to get the dataset.

作者，你好，我给readme中提到的邮箱发送了邮件，但是没有回复，您能发一份处理过的Synapse数据给我吗，我的邮箱地址是 [qbwang@whu.edu.cn](mailto:qbwang@whu.edu.cn). 非常感谢！

**Comment by 870572761** [comment]
你好作者，我按照readme的方法没有成功下载到数据集，您能发一份数据集给我吗？我保证只用于研究与学习，我的邮箱地址是20203100347@hainan.edu.cn
