### ISSUE TITLE
config that works on images 512, 512?

### ISSUE THREAD

**Issue by yarinbar** [HuCaoFighting/Swin-Unet#99]
Hi i am using your repo for research and i am working with a 512 by 512 images, I am having a really hard time adapting the network architecture. I tried #12 but it didnt work - i tried to resize the images to 504x504 or 336x336 that divides by 28 but it didnt work.

Currently i am using resize on the input, but that is not optimal to say the least. 

Did someone get around this issue?

**Comment by kushiluv** [comment]
I'm facing the same issue.

**Comment by yarinbar** [comment]
> I'm facing the same issue.

Try changing window size to a logarithm of 512, like 4, 8, 16 etc. Worked for me
